// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App = (function(_super) {
    __extends(App, _super);

    function App() {
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.initialize = function() {
      var deck;
      this.set('deck', deck = new Deck());
      this.set('playerHand', deck.dealPlayer());
      this.set('dealerHand', deck.dealDealer());
      return this.on('busted', this.gameOver, this);
    };

    App.prototype.events = {
      'stand': function() {
        return (this.get('dealerHand')).complete();
      },
      'restart': function() {
        return this.initialize();
      }
    };

    App.prototype.gameOver = function() {
      return this.trigger('gameOver');
    };

    App.prototype.redeal = function() {
      if ((this.get('deck')).length > 10) {
        this.set('playerHand', (this.get('deck')).dealPlayer());
        return this.set('dealerHand', (this.get('deck')).dealDealer());
      } else {
        return this.intitialize();
      }
    };

    return App;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=App.map
